const cityMapping = {
  Київська: "Kyiv",
  Сумська: "Sumy",
  Харківська: "Kharkiv",
  Чернігівська: "Chernihiv",
  Луганська: "Luhansk",
  Донецька: "Donetsk",
  Кримська: "Simferopol",
  Одеська: "Odesa",
  Ужгородська: "Uzhhorod",
  Полтавська: "Poltava",
  Дніпропетровська: "Dnipro",
  Запорізька: "Zaporizhzhia",
  Херсонська: "Kherson",
  Миколаївська: "Mykolaiv",
  Кіровоградська: "Kropyvnytskyi",
  Луцька: "Lutsk",
  Львівська: "Lviv",
  "Івано-Франківська": "Ivano-Frankivsk",
  Чернівецька: "Chernivtsi",
  Тернопільська: "Ternopil",
  Рівненська: "Rivne",
  Хмельницька: "Khmelnytskyi",
  Житомирська: "Zhytomyr",
  Черкасська: "Cherkasy",
  Вінницька: "Vinnytsia",
  "М.Київ": "Kyivska",
};

export default cityMapping;
